"""empty message

Revision ID: b99cf4cf0617
Revises: 0bc0c17da4e5
Create Date: 2020-09-11 12:10:26.022690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99cf4cf0617'
down_revision = '0bc0c17da4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('type', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'type')
    # ### end Alembic commands ###
